steps:
  run-tests:
    image: nestybox/ubuntu-jammy-systemd-docker:latest
    commands:
      - dockerd &
      - sleep 15
      - cd contract-tests
      - docker compose up -V  --abort-on-container-exit
    pull: true
when:
  - event: push
    branch: master
